################################################################################
## Comment

# Speak your mind with the hash symbol. They go from the symbol to the end of
# the line.


################################################################################
## Table

# Tables (also known as hash tables or dictionaries) are collections of
# key/value pairs. They appear in square brackets on a line by themselves.

asdfpoin1!@ j= ;alskjfasdf

[table]

key = "value" # Yeah, you can do this.
